# Uncomment the next line to define a global platform for your project
platform :ios, '14.5'

target 'TestApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SduiLib', :path => '../sdui_module/sdui_ios'

end
